// Driver data organized by metro lines
const metroDrivers = {
    M1: [
        { id: "M1D001", fullName: "Ahmet Yılmaz" },
        { id: "M1D002", fullName: "Mehmet Demir" },
        { id: "M1D003", fullName: "Ayşe Kara" },
        { id: "M1D004", fullName: "Fatma Çelik" },
        { id: "M1D005", fullName: "Ali Öztürk" },
        { id: "M1D006", fullName: "Zeynep Aydın" },
        { id: "M1D007", fullName: "Mustafa Yıldız" },
        { id: "M1D008", fullName: "Emine Şahin" },
        { id: "M1D009", fullName: "Hüseyin Arslan" },
        { id: "M1D010", fullName: "Hatice Güneş" },
        { id: "M1D011", fullName: "İbrahim Koç" },
        { id: "M1D012", fullName: "Sevim Erdoğan" },
        { id: "M1D013", fullName: "Osman Kaya" },
        { id: "M1D014", fullName: "Aysel Yavuz" },
        { id: "M1D015", fullName: "Murat Özdemir" },
        { id: "M1D016", fullName: "Elif Doğan" },
        { id: "M1D017", fullName: "Hasan Şen" },
        { id: "M1D018", fullName: "Seda Aksoy" },
        { id: "M1D019", fullName: "Kemal Acar" },
        { id: "M1D020", fullName: "Derya Çetin" },
        { id: "M1D021", fullName: "Serkan Tekin" },
        { id: "M1D022", fullName: "Gül Korkmaz" },
        { id: "M1D023", fullName: "Emre Yalçın" },
        { id: "M1D024", fullName: "Sibel Aktaş" },
        { id: "M1D025", fullName: "Burak Özkan" },
        { id: "M1D026", fullName: "Merve Aslan" },
        { id: "M1D027", fullName: "Cem Demirci" },
        { id: "M1D028", fullName: "Deniz Yıldırım" },
        { id: "M1D029", fullName: "Tuncay Güler" },
        { id: "M1D030", fullName: "Esra Çakır" },
        { id: "M1D031", fullName: "Onur Tunç" },
        { id: "M1D032", fullName: "Melek Özcan" },
        { id: "M1D033", fullName: "Tolga Kurt" },
        { id: "M1D034", fullName: "Pınar Sarı" },
        { id: "M1D035", fullName: "Serdar Polat" },
        { id: "M1D036", fullName: "Gamze Avcı" },
        { id: "M1D037", fullName: "Erkan Yalın" },
        { id: "M1D038", fullName: "Canan Koçak" },
        { id: "M1D039", fullName: "Volkan Ateş" },
        { id: "M1D040", fullName: "Şeyma Demir" }
    ],
    M2: [
        { id: "M2D001", fullName: "Mehmet Yılmaz" },
        { id: "M2D002", fullName: "Ayşe Demir" },
        { id: "M2D003", fullName: "Ali Kara" },
        { id: "M2D004", fullName: "Fatma Çelik" },
        { id: "M2D005", fullName: "Ahmet Öztürk" },
        { id: "M2D006", fullName: "Zeynep Aydın" },
        { id: "M2D007", fullName: "Mustafa Yıldız" },
        { id: "M2D008", fullName: "Emine Şahin" },
        { id: "M2D009", fullName: "Hüseyin Arslan" },
        { id: "M2D010", fullName: "Hatice Güneş" },
        { id: "M2D011", fullName: "İbrahim Koç" },
        { id: "M2D012", fullName: "Sevim Erdoğan" },
        { id: "M2D013", fullName: "Osman Kaya" },
        { id: "M2D014", fullName: "Aysel Yavuz" },
        { id: "M2D015", fullName: "Murat Özdemir" },
        { id: "M2D016", fullName: "Elif Doğan" },
        { id: "M2D017", fullName: "Hasan Şen" },
        { id: "M2D018", fullName: "Seda Aksoy" },
        { id: "M2D019", fullName: "Kemal Acar" },
        { id: "M2D020", fullName: "Derya Çetin" },
        { id: "M2D021", fullName: "Serkan Tekin" },
        { id: "M2D022", fullName: "Gül Korkmaz" },
        { id: "M2D023", fullName: "Emre Yalçın" },
        { id: "M2D024", fullName: "Sibel Aktaş" },
        { id: "M2D025", fullName: "Burak Özkan" },
        { id: "M2D026", fullName: "Merve Aslan" },
        { id: "M2D027", fullName: "Cem Demirci" },
        { id: "M2D028", fullName: "Deniz Yıldırım" },
        { id: "M2D029", fullName: "Tuncay Güler" },
        { id: "M2D030", fullName: "Esra Çakır" },
        { id: "M2D031", fullName: "Onur Tunç" },
        { id: "M2D032", fullName: "Melek Özcan" },
        { id: "M2D033", fullName: "Tolga Kurt" },
        { id: "M2D034", fullName: "Pınar Sarı" },
        { id: "M2D035", fullName: "Serdar Polat" },
        { id: "M2D036", fullName: "Gamze Avcı" },
        { id: "M2D037", fullName: "Erkan Yalın" },
        { id: "M2D038", fullName: "Canan Koçak" },
        { id: "M2D039", fullName: "Volkan Ateş" },
        { id: "M2D040", fullName: "Şeyma Demir" }
    ],
    M3: [
        { id: "M3D001", fullName: "Ali Yılmaz" },
        { id: "M3D002", fullName: "Ayşe Demir" },
        { id: "M3D003", fullName: "Mehmet Kara" },
        { id: "M3D004", fullName: "Fatma Çelik" },
        { id: "M3D005", fullName: "Ahmet Öztürk" },
        { id: "M3D006", fullName: "Zeynep Aydın" },
        { id: "M3D007", fullName: "Mustafa Yıldız" },
        { id: "M3D008", fullName: "Emine Şahin" },
        { id: "M3D009", fullName: "Hüseyin Arslan" },
        { id: "M3D010", fullName: "Hatice Güneş" },
        { id: "M3D011", fullName: "İbrahim Koç" },
        { id: "M3D012", fullName: "Sevim Erdoğan" },
        { id: "M3D013", fullName: "Osman Kaya" },
        { id: "M3D014", fullName: "Aysel Yavuz" },
        { id: "M3D015", fullName: "Murat Özdemir" },
        { id: "M3D016", fullName: "Elif Doğan" },
        { id: "M3D017", fullName: "Hasan Şen" },
        { id: "M3D018", fullName: "Seda Aksoy" },
        { id: "M3D019", fullName: "Kemal Acar" },
        { id: "M3D020", fullName: "Derya Çetin" },
        { id: "M3D021", fullName: "Serkan Tekin" },
        { id: "M3D022", fullName: "Gül Korkmaz" },
        { id: "M3D023", fullName: "Emre Yalçın" },
        { id: "M3D024", fullName: "Sibel Aktaş" },
        { id: "M3D025", fullName: "Burak Özkan" },
        { id: "M3D026", fullName: "Merve Aslan" },
        { id: "M3D027", fullName: "Cem Demirci" },
        { id: "M3D028", fullName: "Deniz Yıldırım" },
        { id: "M3D029", fullName: "Tuncay Güler" },
        { id: "M3D030", fullName: "Esra Çakır" },
        { id: "M3D031", fullName: "Onur Tunç" },
        { id: "M3D032", fullName: "Melek Özcan" },
        { id: "M3D033", fullName: "Tolga Kurt" },
        { id: "M3D034", fullName: "Pınar Sarı" },
        { id: "M3D035", fullName: "Serdar Polat" },
        { id: "M3D036", fullName: "Gamze Avcı" },
        { id: "M3D037", fullName: "Erkan Yalın" },
        { id: "M3D038", fullName: "Canan Koçak" },
        { id: "M3D039", fullName: "Volkan Ateş" },
        { id: "M3D040", fullName: "Şeyma Demir" }
    ],
    M4: [
        { id: "M4D001", fullName: "Ahmet Yılmaz" },
        { id: "M4D002", fullName: "Ayşe Demir" },
        { id: "M4D003", fullName: "Mehmet Kara" },
        { id: "M4D004", fullName: "Fatma Çelik" },
        { id: "M4D005", fullName: "Ali Öztürk" },
        { id: "M4D006", fullName: "Zeynep Aydın" },
        { id: "M4D007", fullName: "Mustafa Yıldız" },
        { id: "M4D008", fullName: "Emine Şahin" },
        { id: "M4D009", fullName: "Hüseyin Arslan" },
        { id: "M4D010", fullName: "Hatice Güneş" },
        { id: "M4D011", fullName: "İbrahim Koç" },
        { id: "M4D012", fullName: "Sevim Erdoğan" },
        { id: "M4D013", fullName: "Osman Kaya" },
        { id: "M4D014", fullName: "Aysel Yavuz" },
        { id: "M4D015", fullName: "Murat Özdemir" },
        { id: "M4D016", fullName: "Elif Doğan" },
        { id: "M4D017", fullName: "Hasan Şen" },
        { id: "M4D018", fullName: "Seda Aksoy" },
        { id: "M4D019", fullName: "Kemal Acar" },
        { id: "M4D020", fullName: "Derya Çetin" },
        { id: "M4D021", fullName: "Serkan Tekin" },
        { id: "M4D022", fullName: "Gül Korkmaz" },
        { id: "M4D023", fullName: "Emre Yalçın" },
        { id: "M4D024", fullName: "Sibel Aktaş" },
        { id: "M4D025", fullName: "Burak Özkan" },
        { id: "M4D026", fullName: "Merve Aslan" },
        { id: "M4D027", fullName: "Cem Demirci" },
        { id: "M4D028", fullName: "Deniz Yıldırım" },
        { id: "M4D029", fullName: "Tuncay Güler" },
        { id: "M4D030", fullName: "Esra Çakır" },
        { id: "M4D031", fullName: "Onur Tunç" },
        { id: "M4D032", fullName: "Melek Özcan" },
        { id: "M4D033", fullName: "Tolga Kurt" },
        { id: "M4D034", fullName: "Pınar Sarı" },
        { id: "M4D035", fullName: "Serdar Polat" },
        { id: "M4D036", fullName: "Gamze Avcı" },
        { id: "M4D037", fullName: "Erkan Yalın" },
        { id: "M4D038", fullName: "Canan Koçak" },
        { id: "M4D039", fullName: "Volkan Ateş" },
        { id: "M4D040", fullName: "Şeyma Demir" }
    ],
    M5: [
        { id: "M5D001", fullName: "Ahmet Yılmaz" },
        { id: "M5D002", fullName: "Ayşe Demir" },
        { id: "M5D003", fullName: "Mehmet Kara" },
        { id: "M5D004", fullName: "Fatma Çelik" },
        { id: "M5D005", fullName: "Ali Öztürk" },
        { id: "M5D006", fullName: "Zeynep Aydın" },
        { id: "M5D007", fullName: "Mustafa Yıldız" },
        { id: "M5D008", fullName: "Emine Şahin" },
        { id: "M5D009", fullName: "Hüseyin Arslan" },
        { id: "M5D010", fullName: "Hatice Güneş" },
        { id: "M5D011", fullName: "İbrahim Koç" },
        { id: "M5D012", fullName: "Sevim Erdoğan" },
        { id: "M5D013", fullName: "Osman Kaya" },
        { id: "M5D014", fullName: "Aysel Yavuz" },
        { id: "M5D015", fullName: "Murat Özdemir" },
        { id: "M5D016", fullName: "Elif Doğan" },
        { id: "M5D017", fullName: "Hasan Şen" },
        { id: "M5D018", fullName: "Seda Aksoy" },
        { id: "M5D019", fullName: "Kemal Acar" },
        { id: "M5D020", fullName: "Derya Çetin" },
        { id: "M5D021", fullName: "Serkan Tekin" },
        { id: "M5D022", fullName: "Gül Korkmaz" },
        { id: "M5D023", fullName: "Emre Yalçın" },
        { id: "M5D024", fullName: "Sibel Aktaş" },
        { id: "M5D025", fullName: "Burak Özkan" },
        { id: "M5D026", fullName: "Merve Aslan" },
        { id: "M5D027", fullName: "Cem Demirci" },
        { id: "M5D028", fullName: "Deniz Yıldırım" },
        { id: "M5D029", fullName: "Tuncay Güler" },
        { id: "M5D030", fullName: "Esra Çakır" },
        { id: "M5D031", fullName: "Onur Tunç" },
        { id: "M5D032", fullName: "Melek Özcan" },
        { id: "M5D033", fullName: "Tolga Kurt" },
        { id: "M5D034", fullName: "Pınar Sarı" },
        { id: "M5D035", fullName: "Serdar Polat" },
        { id: "M5D036", fullName: "Gamze Avcı" },
        { id: "M5D037", fullName: "Erkan Yalın" },
        { id: "M5D038", fullName: "Canan Koçak" },
        { id: "M5D039", fullName: "Volkan Ateş" },
        { id: "M5D040", fullName: "Şeyma Demir" }
    ]
};

// Function to get available drivers for a specific metro line
const getDriversForLine = (line) => {
    return metroDrivers[line] || [];
};

// Function to get random drivers from a line
const getRandomDrivers = (line, count) => {
    const drivers = metroDrivers[line] || [];
    const shuffled = [...drivers].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
};

// Export the functions and data
export { getDriversForLine, getRandomDrivers };
